name: static check
on: pull_request

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: check
      uses: grandcolline/golang-github-actions@fix/outputs
      with:
        run: lint
        token: ${{ secrets.GITHUB_TOKEN }}
        comment: false
