name: static check
on: pull_request

jobs:
  imports:
    name: Imports
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: check
      uses: grandcolline/golang-github-actions@fix/outputs
      with:
        run: imports
        token: ${{ secrets.GITHUB_TOKEN }}
        comment: false
